name: PersonalWarp
main: com.github.risen619.Main
version: 1.0.0
commands:
    pwarp:
        description: Teleports you to warp location.
        usage: /<command> <name> <player>
        aliases: [p, warp]
    pwarps:
        description: Lists all public warps.
        usage: /<command>
        aliases: [pall, warps]
    pmywarps: 
        description: Lists all your warps.
        usage: /<command>
        aliases: [pmy]
    psetwarp:
        description: Sets warp.
        usage: /<command> <name> [private|public]
        aliases: [pset, setwarp]
    pdelwarp:
        description: Deletes warp.
        usage: /<command> <name>
        aliases: [pdel, delwarp]
    paddmember:
        description: Adds member to your warp.
        usage: /<command> <name> <player>
        aliases: [padd]
    pteleporter:
        description: Gives you clickable sign, which will teleport you to your warp.
        usage: /<command> <name> [owner|members|all] <block>
        aliases: [pt, ps]
    prandom:
        description: Teleports you to random location.
        usage: /<command>
        aliases: [pr, rand, rtp]