name: PersonalWarp
main: com.github.risen619.Main
version: 1.0.0
commands:
    pwarp:
        description: Teleports you to warp location.
        usage: /<command> <name> <player>
        aliases: [p]
    pwarps:
        description: Lists all public warps.
        usage: /<command>
        aliases: [pall]
    pmywarps: 
        description: Lists all your warps.
        usage: /<command>
        aliases: [pmy]
    psetwarp:
        description: Sets warp.
        usage: /<command> <name> [private|public]
        aliases: [pset]
    pdelwarp:
        description: Deletes warp.
        usage: /<command> <name>
        aliases: [pdel]
    paddmember:
        description: Adds member to your warp.
        usage: /<command> <name> <player>
        aliases: [padd]
    psign:
        description: Gives you clickable sign, which will teleport you to your warp.
        usage: /<command> <name> [owner|members|all] <block>
        aliases: [ps]